version = 0.1

[default.deploy.parameters]
stack_name = "image-processor-app"
resolve_s3 = true
s3_prefix = "image-processor-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SourceBucketName=\"image-source-priye-2024\" DestBucketName=\"image-thumbnails-priye-2024\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
